services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  neo4j:
    image: neo4j:5.13.0
    environment:
      NEO4J_AUTH: neo4j/letmein
      NEO4J_dbms_security_auth__minimum__password__length: "1"
    ports:
      - "7687:7687"
      - "7474:7474"

  python-api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - elasticsearch
      - neo4j
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ../frontend
    command: npm run dev -- --host --port 3000
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
